### ISSUE TITLE
Cannot build Angular project

### ISSUE THREAD

**Issue by romko391** [fathyb/parcel-plugin-angular#5]
Getting this while trying to build a project:
**×  C:\Playground\parcel-test\src\main.ts: Error: connect EPERM /**

![image](https://user-images.githubusercontent.com/1271013/36685214-53575138-1b2b-11e8-8525-cb04cfa00362.png)

This is not reproducible when I remove the `parcel-plugin-angular` from devDependencies.
Anybody's got an idea?

```
"parcel-bundler": "^1.6.2"
"parcel-plugin-angular": "^0.5.0"
```

**Comment by woubuc** [comment]
I have the same issue.

**Comment by fathyb** [comment]
Could you install `parcel-plugin-typescript` and upgrade to `parcel-plugin-angular@0.5.1-next.13` to see if it fixes it?

**Comment by jimbuck** [comment]
I get the same issue from above. After installing `parcel-plugin-typescript` and upgrading to `parcel-plugin-angular@0.5.1-next.13` it compiles successfully. Unfortunately when running the app I get the following error:

```
..\node_modules\@angular\compiler\fesm5\compiler.js:11902 Uncaught Error: No NgModule metadata found for 'function (){}'.
    at e.resolve (..\node_modules\@angular\compiler\fesm5\compiler.js:11902)
    at e.getNgModuleMetadata (..\node_modules\@angular\compiler\fesm5\compiler.js:10544)
    at e._loadModules (..\node_modules\@angular\compiler\fesm5\compiler.js:23876)
    at e._compileModuleAndComponents (..\node_modules\@angular\compiler\fesm5\compiler.js:23857)
    at e.compileModuleAsync (..\node_modules\@angular\compiler\fesm5\compiler.js:23817)
    at r.compileModuleAsync (..\node_modules\@angular\platform-browser-dynamic\fesm5\platform-browser-dynamic.js:143)
    at e.bootstrapModule (..\node_modules\@angular\core\fesm5\core.js:4344)
    at Object.parcelRequire.ZCfc.@angular/platform-browser-dynamic (main.ts:10)
```

Previously I had my app running using inline template strings (only change now is that I am using `templateUrl` for my components.

**Comment by jimbuck** [comment]
Actually, this error is present when building:

```
Compile error Error: TypeError: Cannot read property 'rootDir' of undefined
    at new Asset (C:\Project\node_modules\parcel-bundler\src\Asset.js:24:47)
    at new HTMLAsset (C:\Project\node_modules\parcel-bundler\src\assets\HTMLAsset.js:76:5)
    at new TemplateAsset (C:\Project\node_modules\parcel-plugin-angular\build\frontend\assets\template.js:9:1)
    at Object.<anonymous> (C:\Project\node_modules\parcel-plugin-angular\build\frontend\loaders\template.js:15:15)
```

Looks like the constructor parameters are different between TemplateAsset and HtmlAsset.

In case it helps:
```
"parcel-bundler": "^1.9.7",
"parcel-plugin-angular": "^0.5.1-next.13",
"parcel-plugin-typescript": "^1.0.0",
"typescript": "^2.9.2"
```
